version: "3.9"

services:
  pokeland_database:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app_user
      POSTGRES_DB: app_db
      POSTGRES_PASSWORD: app_password
    ports:
      - "5432:5432"

  pokeland_api:
    image: pokeland_api
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - pokeland_database
    environment:
      DB_URL: postgresql+psycopg://app_user:app_password@pokeland_database:5432/app_db
      SECRET_KEY: secret

  pokeland_ui:
    image: pokeland_ui
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - pokeland_api
    environment:
      NEXT_PUBLIC_API_URL: http://pokeland_api:8000

volumes:
  pgdata: