services:
  pokeland_database:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app_user
      POSTGRES_DB: app_db
      POSTGRES_PASSWORD: app_password
    ports:
      - "5432:5432"

  pokeland_api:
    image: pokeland_api
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    entrypoint: ./entrypoint.sh
    depends_on:
      - pokeland_database
    environment:
      DATABASE_URL: postgresql+psycopg://app_user:app_password@pokeland_database:5432/app_db
      SECRET_KEY: secret

volumes:
  pgdata: